const COLORS = {
  COLOR_TRANSPARENT: 'transparent',
  COLOR_BLACK: '#000000',
  COLOR_WHITE: '#ffffff',
  COLOR_LOADER: 'rgba(0, 0, 0, 0.7)',
  COLOR_LIGHT_GRAY: '#9191A1',
  COLOR_TEXT_OFF_WHITE: '#EBEBEB',
  COLOR_RED: '#D32F2F',
  COLOR_BROWN:'#9e3154',
  COLOR_LIGHTBROWN:'#c495a4',
  COLOR_STONE:'#B7B09C',
  COLOR_GRAY:'#f0f4f4'
};


export default COLORS;
